route:
    receiver: alert-emailer
    group_by: ['alertname', 'priority']
    group_wait: 10s
    repeat_interval: 30m
    routes:
      - receiver: alert-slack
      # Send severity=slack alerts to slack.
        match:
          severity: slack
        group_wait: 10s
        repeat_interval: 1m
 
receivers:
    - name: alert-emailer
      email_configs:
      - to: test@thingsboard.io
        send_resolved: false
        from: test@thingsboard.io
        smarthost: smtp.gmail.com:465
        require_tls: true
        auth_username: test@thingsboard.io
        auth_identity: "test@thingsboard.io"
        auth_password: "test"
    - name: alert-slack
      slack_configs:
      - api_url: WEB HOOK URL
        channel: 
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
          text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

          *Description:* {{ .Annotations.description }}

          *Details:*
            {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
            {{ end }}
          {{ end }}