global:
  resolve_timeout: 1m

route:
  receiver: alert-slack
  group_interval: 1m
  group_wait: 10s
  repeat_interval: 1m
  group_by: ['alertname', 'priority']
receivers:
    - name: alert-slack
      slack_configs:
        - send_resolved: true
          api_url: 'WEB_HOOK_URL'
          channel:
          title: |-
            [{{ .Status | toUpper }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          text: >-
            {{ range .Alerts -}}

            *Description:* {{ .Annotations.description }}

            *Details:*
              {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
              {{ end }}
            {{ end }}
